// Rebuild <skins dir>/manifest.js from the skin packages on disk.
// Run after adding or removing a skin folder (or double-click sync-skins.cmd).
//
// Skins live outside the app, at %USERPROFILE%\.mirasim\skins by default.
// Override with MIRASIM_SKINS_DIR.
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

export const SKINS_DIR = process.env.MIRASIM_SKINS_DIR
  || path.join(os.homedir(), '.mirasim', 'skins');

export function sync(dir = SKINS_DIR) {
  fs.mkdirSync(dir, { recursive: true });
  const skins = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const jsonPath = path.join(dir, entry.name, 'skin.json');
    const cssPath = path.join(dir, entry.name, 'skin.css');
    if (!fs.existsSync(jsonPath)) continue;
    let meta;
    try {
      meta = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
    } catch (e) {
      console.warn(`skip ${entry.name}: skin.json is not valid JSON (${e.message})`);
      continue;
    }
    if (!fs.existsSync(cssPath)) {
      console.warn(`skip ${entry.name}: no skin.css`);
      continue;
    }
    skins.push({
      name: entry.name,
      label: String(meta.label || entry.name),
      author: String(meta.author || ''),
      description: String(meta.description || ''),
      accent: String(meta.accent || '#888'),
    });
  }
  skins.sort((a, b) => a.name.localeCompare(b.name));
  fs.writeFileSync(path.join(dir, 'manifest.js'),
    '// generated by sync.mjs — do not edit\n' +
    'window.__mirasimSkins = ' + JSON.stringify(skins, null, 2) + ';\n', 'utf8');
  console.log(`manifest.js: ${skins.length} skin(s) — ${skins.map((s) => s.name).join(', ') || '(none)'}`);
  return skins;
}

if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) sync();
